# Generated by Django 3.0.2 on 2020-01-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_type',
            field=models.IntegerField(null=True),
        ),
    ]
