# Generated by Django 3.0.2 on 2020-01-21 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_questions_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='essay',
        ),
    ]
