# Generated by Django 3.0.2 on 2020-01-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.CharField(max_length=40, null=True)),
                ('question', models.TextField(null=True)),
                ('question_type', models.IntegerField(null=True)),
                ('op1', models.CharField(max_length=40, null=True)),
                ('op2', models.CharField(max_length=40, null=True)),
                ('op3', models.CharField(max_length=40, null=True)),
                ('op4', models.CharField(max_length=40, null=True)),
                ('ans', models.CharField(max_length=40, null=True)),
                ('weightage', models.IntegerField(null=True)),
            ],
        ),
    ]
